version: '3'
services:
    redis: 
      image: 'redis:latest'
    nginx:
       restart: always
       build:
         dockerfile: Dockerfile.dev
         context: ./nginx  
       ports:
         - "4000:80"  
       depends_on:
         - 'api'
         - 'client' 
       expose:
         - "4000"
    api:
       build:
        dockerfile: Dockerfile.dev
        context: ./server 
       volumes:
          - /app/node_modules 
          - ./server:/app 
       environment: 
          - REDIS_HOST=redis
          - REDIS_PORT=6379
       expose:
          - "5000"  
    client:
       build: 
         dockerfile: Dockerfile.dev
         context: ./client
       volumes:
         - /app/node_modules
         - ./client:/app
       expose:
         - "3000"  
            
                
             