# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
      AWS_REGION: us-east-1                  # set this to your preferred AWS region, e.g. us-west-1
      APPLICATION_NAME: multi-docker
      ENVIRONMENT_NAME: Multidocker-env-1
jobs:
  
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #      - name: Build and test
  #        id: docker_build_tests
  #        uses: actions/checkout@v3
  #      - name: Building for test   
  #        run: docker build -t ${{ secrets.DOCKER_ID }}/react-test  -f   ./client/Dockerfile.dev ./client 
  #      - name: Run tests
  #        run: docker run ${{ secrets.DOCKER_ID }}/react-test npm test -- --coverage
           
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo 
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: client
          file: client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/multi-client:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/multi-server:latest 
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/multi-nginx:latest 
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} 
          # set this to your Amazon ECR repository name
     
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Generate deployment package
          run: zip -r deploy.zip . -x '*.git*'
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        - name: Upload on beanstalk
          uses: einaregilsson/beanstalk-deploy@v16  
          with:
             application_name: ${{ env.APPLICATION_NAME }}
             environment_name: ${{ env.ENVIRONMENT_NAME }}
             region: us-east-1
             deployment_package: deploy.zip
       
          


